import React,{useEffect,useMemo,useState}from'react';
import Papa from'papaparse';import{AreaChart,Area,BarChart,Bar,Cell,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer}from'recharts';
import{Sun,Home,Plug,Zap,Coins,Upload,Settings,Lock,BarChart3,TrendingUp,Database,LogOut,Info}from'lucide-react';import seed from'./seed.json';
const YEAR_COLORS=['#2563eb','#f59e0b','#10b981','#8b5cf6','#ef4444','#06b6d4'];
const wholeKwh=(value,name)=>[`${Math.round(Number(value)||0).toLocaleString('de-CH')} kWh`,name];
const compareKwh=(value,name)=>[`${Math.round(Number(value)||0).toLocaleString('de-CH')} kWh`,name];
const DEFAULT={commission:'2024-04-12',investment:72690,grant:11795.90,tariffs:{2024:{nt:.2495,ht:.2905,solar:.23,feed:.185},2025:{nt:.2438,ht:.2845,solar:.23,feed:.10},2026:{nt:.2363,ht:.2773,solar:.23,feed:.08}}};
const fmt=(n,d=0)=>new Intl.NumberFormat('de-CH',{maximumFractionDigits:d,minimumFractionDigits:d}).format(n||0);const money=n=>`CHF ${fmt(n,2)}`;const pct=n=>`${fmt(n,1)} %`;const months=['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'];
function merge(a,b){const m=new Map([...a,...b].map(x=>[x.date,x]));return[...m.values()].sort((x,y)=>x.date.localeCompare(y.date))}
function aggregate(days,settings){const mm={},yy={};for(const x of days){const y=+x.date.slice(0,4),mo=+x.date.slice(5,7);const t=settings.tariffs?.[y]||{};const rev=x.selfConsumption*(t.solar||0)+x.feedIn*(t.feed||0);for(const [k,key] of [[`${y}-${String(mo).padStart(2,'0')}`,mm],[String(y),yy]]){if(!key[k])key[k]={production:0,consumption:0,selfConsumption:0,gridImport:0,feedIn:0,revenue:0};for(const q of['production','consumption','selfConsumption','gridImport','feedIn'])key[k][q]+=x[q]||0;key[k].revenue+=rev}}return{mm,yy}}
const Tip=({text})=><span title={text}><Info size={15}/></span>;
function App(){const[days,setDays]=useState(seed.days);const[settings,setSettings]=useState(DEFAULT);const[page,setPage]=useState('Dashboard');const[token,setToken]=useState('');const[login,setLogin]=useState(false);const[pass,setPass]=useState('');const[status,setStatus]=useState('');const[month,setMonth]=useState(10);const[mode,setMode]=useState('same');const[dashKey,setDashKey]=useState('');
useEffect(()=>{fetch('/api/public-data').then(r=>r.json()).then(x=>{if(x.days?.length)setDays(merge(seed.days,x.days));if(x.settings)setSettings(x.settings)}).catch(()=>{})},[]);
const{mm,yy}=useMemo(()=>aggregate(days,settings),[days,settings]);const last=days.at(-1)?.date||seed.last;const currentKey=last?.slice(0,7);const selectedDashKey=dashKey||currentKey,cur=mm[selectedDashKey]||{};const years=Object.keys(yy).sort();const inv=settings.investment-settings.grant;const totalRev=Object.values(yy).reduce((a,x)=>a+x.revenue,0);const amort=Math.min(100,totalRev/inv*100);
const nav=['Dashboard','Vergleiche','Finanzen','Amortisation'];
const monthlyChart=Array.from({length:12},(_,i)=>{const o={month:months[i]};years.forEach(y=>o[y]=mm[`${y}-${String(i+1).padStart(2,'0')}`]?.production||0);return o});
const daily=days.filter(x=>x.date.startsWith(selectedDashKey)).map(x=>({...x,day:+x.date.slice(8,10)}));
function doLogin(e){e.preventDefault();const password=new FormData(e.currentTarget).get('password')||'';fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})}).then(async r=>{if(!r.ok)throw 0;return r.json()}).then(x=>{setToken(x.token);setLogin(true);setStatus('')}).catch(()=>setStatus('Passwort falsch'))}
function importCsv(file){setStatus('CSV wird geprüft …');Papa.parse(file,{header:true,skipEmptyLines:true,complete:r=>{const d=new Map();const smKey=(r.meta?.fields||[]).find(k=>k.includes('Messung Huawei - currentPower'));for(const row of r.data){if(!row.Date)continue;const date=row.Date.slice(0,10),c=Math.max(0,+row.Consumption||0)*.25/1000,p=Math.max(0,+row.Production||0)*.25/1000;const hasSm=smKey&&row[smKey]!==''&&row[smKey]!=null&&!Number.isNaN(+row[smKey]);const sm=hasSm?+row[smKey]:0;const gi=hasSm?Math.max(0,sm)*.25/1000:Math.max(c-p,0);const fi=hasSm?Math.max(0,-sm)*.25/1000:Math.max(p-c,0);const sc=hasSm?Math.max(p-fi,0):Math.min(c,p);if(!d.has(date))d.set(date,{date,consumption:0,production:0,selfConsumption:0,gridImport:0,feedIn:0,samples:0});const x=d.get(date);x.consumption+=c;x.production+=p;x.selfConsumption+=sc;x.gridImport+=gi;x.feedIn+=fi;x.samples++}const a=[...d.values()].map(x=>{Object.keys(x).forEach(k=>typeof x[k]==='number'&&(x[k]=+x[k].toFixed(3)));return x});const all=merge(days,a);fetch('/api/save-data',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${token}`},body:JSON.stringify({days:all,settings})}).then(q=>{if(!q.ok)throw 0;setDays(all);setStatus(`Import erfolgreich: ${a.length} Tage intervallgenau verarbeitet. Datenstand ${all.at(-1).date}.`) }).catch(()=>setStatus('Speichern fehlgeschlagen. Netlify-Konfiguration prüfen.'))}})}
function saveSettings(){fetch('/api/save-data',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${token}`},body:JSON.stringify({days,settings})}).then(r=>r.ok?setStatus('Einstellungen gespeichert.'):setStatus('Speichern fehlgeschlagen.'))}
return <div className="app"><aside><div className="brand"><Sun/><b>Nesslergraben 8</b><small>Unsere Photovoltaikanlage</small></div>{nav.map(n=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><BarChart3/> {n}</button>)}<div className="spacer"/><button onClick={()=>setPage('Admin')}><Lock/> Admin</button></aside><main><header className="hero"><div><h1>{page==='Admin'?'Admin Bereich':page}</h1><p>{page==='Dashboard'?'Energie gemeinsam sichtbar machen.':''}</p></div><div className="date"><small>Datenstand</small><b>{new Date(last+'T12:00:00').toLocaleDateString('de-CH',{day:'numeric',month:'long',year:'numeric'})}</b></div></header>{page!=='Admin'&&<div className="privacy-note"><b>Datenschutz:</b> Alle Auswertungen zeigen ausschliesslich aggregierte Werte der gesamten Liegenschaft. Einzelne Wohnungs- oder Eigentümerdaten werden nicht veröffentlicht.</div>}{page==='Dashboard'&&<Dashboard/>}{page==='Vergleiche'&&<Compare/>}{page==='Finanzen'&&<Finance/>}{page==='Amortisation'&&<Amort/>}{page==='Admin'&&<Admin/>}</main></div>
function Cards({x=cur}){const aut=x.consumption?x.selfConsumption/x.consumption*100:0,eq=x.production?x.selfConsumption/x.production*100:0;return <div className="cards"><Card icon={<Sun/>} t="PV-Produktion" v={`${fmt(x.production)} kWh`} c="yellow"/><Card icon={<Home/>} t="Eigenverbrauch im Gebäude" v={`${fmt(x.selfConsumption)} kWh`} s={pct(eq)} c="green"/><Card icon={<Plug/>} t="Netzbezug" v={`${fmt(x.gridImport)} kWh`} c="blue"/><Card icon={<Zap/>} t="Einspeisung" v={`${fmt(x.feedIn)} kWh`} c="purple"/><Card icon={<Coins/>} t="Finanzieller Nutzen" v={money(x.revenue)} c="red"/></div>}
function Card({icon,t,v,s,c}){return <div className={`card ${c}`}><div className="ico">{icon}</div><div><small>{t}</small><strong>{v}</strong>{s&&<em>{s}</em>}</div></div>}
function Dashboard(){const dashYear=selectedDashKey.slice(0,4),dashMonth=+selectedDashKey.slice(5,7);const dashYears=[...new Set(Object.keys(mm).map(k=>k.slice(0,4)))].sort();const dashMonths=Object.keys(mm).filter(k=>k.startsWith(`${dashYear}-`)).map(k=>+k.slice(5,7)).sort((a,b)=>a-b);const changeYear=y=>{const available=Object.keys(mm).filter(k=>k.startsWith(`${y}-`)).sort();const same=`${y}-${String(dashMonth).padStart(2,'0')}`;setDashKey(mm[same]?same:available.at(-1)||currentKey)};return <><div className="dashboard-period"><div><b>Zeitraum anzeigen</b><small>Beim Öffnen wird automatisch der aktuellste Monat angezeigt.</small></div><label>Jahr<select value={dashYear} onChange={e=>changeYear(e.target.value)}>{dashYears.map(y=><option key={y} value={y}>{y}</option>)}</select></label><label>Monat<select value={dashMonth} onChange={e=>setDashKey(`${dashYear}-${String(+e.target.value).padStart(2,'0')}`)}>{dashMonths.map(m=><option key={m} value={m}>{months[m-1]}</option>)}</select></label></div><Cards/><section className="grid"><Panel title={`Energiefluss – ${months[dashMonth-1]} ${dashYear}`}><ResponsiveContainer width="100%" height={280}><AreaChart data={daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Legend/><Area dataKey="production" name="Produktion" stackId="a" fill="#fbbf24" stroke="#f59e0b"/><Area dataKey="selfConsumption" name="Eigenverbrauch" fill="#34d399" stroke="#059669"/><Line dataKey="gridImport" name="Netzbezug" stroke="#3b82f6"/></AreaChart></ResponsiveContainer></Panel><Panel title="Kennzahlen"><Kpi n="Autarkiegrad" v={pct(cur.consumption?cur.selfConsumption/cur.consumption*100:0)}/><Kpi n="Eigenverbrauchsquote" v={pct(cur.production?cur.selfConsumption/cur.production*100:0)}/><Kpi n="Gesamtverbrauch" v={`${fmt(cur.consumption)} kWh`}/><Kpi n="Daten seit" v="12.04.2024"/></Panel></section><Panel title="Monatsverlauf Produktion – alle Jahre"><ResponsiveContainer width="100%" height={300}><BarChart data={monthlyChart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={wholeKwh}/><Legend/>{years.map((y,i)=><Bar key={y} dataKey={y} name={y} fill={YEAR_COLORS[i%YEAR_COLORS.length]}/>)}</BarChart></ResponsiveContainer></Panel></>}
function Compare(){const latestYear=years.at(-1);const monthPrefix=`${latestYear}-${String(month).padStart(2,'0')}`;const latestMonthDays=days.filter(x=>x.date.startsWith(monthPrefix));const cutoff=latestMonthDays.length?Math.max(...latestMonthDays.map(x=>+x.date.slice(8,10))):31;const sumRows=y=>{const xs=days.filter(x=>x.date.startsWith(`${y}-${String(month).padStart(2,'0')}`)&&(mode==='full'||+x.date.slice(8,10)<=cutoff));return xs.reduce((a,x)=>{for(const k of['production','consumption','selfConsumption','gridImport','feedIn'])a[k]+=x[k]||0;const t=settings.tariffs?.[y]||{};a.revenue+=(x.selfConsumption||0)*(t.solar||0)+(x.feedIn||0)*(t.feed||0);return a},{year:y,production:0,consumption:0,selfConsumption:0,gridImport:0,feedIn:0,revenue:0})};const rows=years.map(sumRows);return <><div className="toolbar"><label>Monat <select value={month} onChange={e=>setMonth(+e.target.value)}>{months.map((m,i)=><option value={i+1}>{m}</option>)}</select></label><button className={mode==='same'?'primary':''} onClick={()=>setMode('same')}>Gleicher Zeitraum{mode==='same'?` (bis ${cutoff}.)`:''}</button><button className={mode==='full'?'primary':''} onClick={()=>setMode('full')}>Ganzer Monat</button></div><Cards x={rows.at(-1)||{}}/><Panel title={`${months[month-1]} – Vergleich aller Jahre`}><ResponsiveContainer width="100%" height={320}><BarChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year"/><YAxis/><Tooltip formatter={compareKwh}/><Legend/>
<Bar dataKey="production" name="Produktion" fill="#f59e0b"/>
<Bar dataKey="selfConsumption" name="Eigenverbrauch" fill="#10b981"/>
<Bar dataKey="gridImport" name="Netzbezug" fill="#3b82f6"/>
<Bar dataKey="feedIn" name="Einspeisung" fill="#8b5cf6"/></BarChart></ResponsiveContainer></Panel><Panel title="Monatsverlauf Produktion – alle Jahre"><ResponsiveContainer width="100%" height={300}><LineChart data={monthlyChart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={wholeKwh}/><Legend/>{years.map((y,i)=><Line key={y} dataKey={y} name={y} stroke={YEAR_COLORS[i%YEAR_COLORS.length]} strokeWidth={3} dot={{r:3}} activeDot={{r:6}}/>)}</LineChart></ResponsiveContainer></Panel></>}
function Finance(){return <><Cards/><Panel title="Finanzieller Nutzen pro Jahr"><div className="table"><div className="tr head"><span>Jahr</span><span>Solartarif</span><span>EW-Vergütung</span><span>Total</span></div>{years.map(y=>{const t=settings.tariffs[y]||{},x=yy[y];return <div className="tr"><b>{y}</b><span>{money(x.selfConsumption*(t.solar||0))}</span><span>{money(x.feedIn*(t.feed||0))}</span><b>{money(x.revenue)}</b></div>})}</div></Panel></>}
function Amort(){return <><div className="amort"><h2>Amortisation der PV-Anlage</h2><div className="big">{pct(amort)} amortisiert</div><div className="progress"><i style={{width:`${amort}%`}}/></div><div className="stats"><span>Nettoinvestition <b>{money(inv)}</b></span><span>Bisher zurückgeflossen <b>{money(totalRev)}</b></span><span>Noch offen <b>{money(Math.max(0,inv-totalRev))}</b></span></div></div><Panel title="Kumulierte Rückflüsse"><ResponsiveContainer width="100%" height={320}><AreaChart data={years.map((y,i)=>({year:y,value:years.slice(0,i+1).reduce((a,z)=>a+yy[z].revenue,0)}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year"/><YAxis/><Tooltip/><Area dataKey="value" name="Rückfluss CHF"/></AreaChart></ResponsiveContainer></Panel></>}
function Admin(){if(!login)return <div className="login"><Lock/><h2>Geschützter Bereich</h2><form onSubmit={doLogin}><input type="password" name="password" placeholder="Passwort" autoFocus autoComplete="current-password"/><button className="primary">Anmelden</button></form><p className="status">{status}</p></div>;return <><div className="adminTop"><button onClick={()=>{setLogin(false);setToken('')}}><LogOut/> Abmelden</button></div><div className="adminGrid"><Panel title="1. CSV-Daten importieren"><div className="drop"><Upload/><b>Solar-Manager CSV auswählen</b><input type="file" accept=".csv,text/csv" onChange={e=>e.target.files[0]&&importCsv(e.target.files[0])}/><small>Es werden nur aggregierte Gebäudedaten gespeichert. Keine Wohnungs-/Eigentümerdaten.</small></div></Panel><Panel title="2. Stromtarife und Vergütungen"><Tariffs/></Panel><Panel title="3. Investition & Amortisation"><label>Inbetriebnahme<input value={settings.commission} onChange={e=>setSettings({...settings,commission:e.target.value})}/></label><label>Investition brutto CHF<input type="number" value={settings.investment} onChange={e=>setSettings({...settings,investment:+e.target.value})}/></label><label>Einmalvergütung CHF<input type="number" value={settings.grant} onChange={e=>setSettings({...settings,grant:+e.target.value})}/></label><b>Netto: {money(inv)}</b><button className="primary" onClick={saveSettings}>Einstellungen speichern</button></Panel></div><p className="status">{status}</p></>}
function Tariffs(){const add=()=>{const y=Math.max(...Object.keys(settings.tariffs).map(Number))+1;setSettings({...settings,tariffs:{...settings.tariffs,[y]:{nt:0,ht:0,solar:.23,feed:0}}})};const fields=[['nt','Niedertarif (NT)'],['ht','Hochtarif (HT)'],['solar','Solartarif'],['feed','EW-Vergütung']];return <><div className="tariffYears">{Object.entries(settings.tariffs).map(([y,t])=><section className="tariffYear" key={y}><div className="tariffYearHead"><b>{y}</b><span>CHF/kWh</span></div><div className="tariffFields">{fields.map(([k,label])=><label key={k}><span>{label}</span><input type="number" step="0.0001" value={t[k]} onChange={e=>setSettings({...settings,tariffs:{...settings.tariffs,[y]:{...t,[k]:+e.target.value}}})}/></label>)}</div></section>)}</div><button className="addYear" onClick={add}>+ Jahr hinzufügen</button></>}
function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}function Kpi({n,v}){return <div className="kpi"><span>{n}</span><b>{v}</b></div>}
}
export default App;
